describe('template spec', () => {
  it('passes', () => {
    cy.visit('https://provaqa.fandi.com.br/')
    cy.viewport(1920, 1080)
    cy.get('.btn').click()
    cy.wait(1000)
    cy.get('#botaoNovoVeiculo').click()
    cy.wait(10000)
    cy.get('#novaFamilia').should('be.visible')
    cy.get('#novoFabricante').should('be.visible')
    cy.get('#novoFabricante').should('be.visible')
    cy.get('#divIncluindoNovoModelo > :nth-child(3) > :nth-child(2) > .form-group > .form-control').should('be.visible')
    cy.get(':nth-child(4) > :nth-child(1) > .form-group > .form-control').should('be.visible')
    cy.get(':nth-child(4) > :nth-child(2) > .form-group > .form-control').should('be.visible')
    cy.get(':nth-child(5) > :nth-child(1) > .form-group > .form-control').should('be.visible')
    cy.get(':nth-child(5) > :nth-child(2) > .form-group > .form-control').should('be.visible')
    cy.get(':nth-child(6) > :nth-child(1) > .form-group > .form-control').should('be.visible')
    cy.get(':nth-child(5) > :nth-child(2) > .form-group > .form-control').should('be.visible')
    cy.get(':nth-child(6) > :nth-child(1) > .form-group > .form-control').should('be.visible')
    cy.get(':nth-child(6) > :nth-child(2) > .form-group > .form-control').should('be.visible')
    cy.get('#btnCancelar').should('be.visible').click()
  })
})